package com.example.shopper.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "shopping_item")

//table representation
data class ShoppingItem(
    @ColumnInfo(name = "Item")  //col name
    var itemName:String,
    @ColumnInfo(name = "Amount")
    var amount:Int)
{

//primary key
@PrimaryKey(autoGenerate = true)   //autogenerated by room
    var id:Int?=null

}